[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=fust-ld=lld"]