application_port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
telemetry:
  otlp_endpoint: "https://api.honeycomb.io/v1/traces"
  honeycomb_api_key: "COq84NfvgsAeYIZqaqB1TH"
  dataset_name: "zero2prod"