services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
      DB_PORT: 5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
  application:
    image: zero2prod
    ports:
      - 8080:8080
    environment:
      APP_REDIS_URI: redis://redis:6379