services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
  application:
    image: zero2prod
    ports:
      - 8080:8080
    environment:
      APP_DATABASE__USE_LOCAL: false
      AWS_ACCESS_KEY_ID: AKIAW22GPLBZU3RNC67G
      AWS_SECRET_ACCESS_KEY: localstack
      AWS_REGION: us-east-1