name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  init:
    name: CIBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt,tarpaulin
      - uses: Swatinem/rust-cache@v2
      - name: Initialize database
        run: cargo install --version="~0.7" sqlx-cli --no-default-features --features rustls,postgres
      - name: Initialize database
        run: ./scripts/init_db.sh
      - name: Enforce formatting
        run: cargo fmt --check
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace